#!/usr/bin/env python3

import fdb

fdb.api_version(710)
db = fdb.open("/fdb-cluster-config/cluster-file")

#
#    OTHER = 0
#    REBALANCE_DISK,
#    REBALANCE_READ,
#    REBALANCE_WRITE,
#    MERGE_SHARD,
#    SIZE_SPLIT,
#    WRITE_SPLIT,
#    TENANT_SPLIT,
#    __COUNT

tr = db.create_transaction()
tr.options.set_access_system_keys()
REBALANCE_SETTINGS_KEY = b"\xff\x02/r"
for k, v in tr.get_range_startswith(REBALANCE_SETTINGS_KEY, 10000):
    print(f"{k} {v}")
